import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Instagram from '@/assets/square-instagram-brands-solid.svg';
import Twitter from '@/assets/square-twitter-brands-solid.svg';
import LinkedIn from '@/assets/linkedin-brands-solid.svg';
import Github from '@/assets/square-github-brands-solid.svg';
const Footer = () => {
    return (_jsx("footer", { children: _jsxs("div", { className: 'footer-parent-container', children: [_jsxs("div", { className: 'footer-container', children: [_jsxs("div", { className: 'left-side-footer', children: [_jsx("h3", { children: "Nuestras Redes" }), _jsxs("div", { className: 'social-media', children: [_jsx("img", { src: Instagram, alt: "instagram-logo" }), _jsx("p", { children: "@YellowJack" })] }), _jsxs("div", { className: 'social-media', children: [_jsx("img", { src: Twitter, alt: "twitter-logo" }), _jsx("p", { children: "@YellowJack" })] })] }), _jsxs("div", { className: "middle-footer", children: [_jsx("p", { children: "Trabaja con nosotros" }), _jsx("p", { children: "Pol\u00EDtica de privacidad" }), _jsx("p", { children: "Te\u0301rminos de uso" })] }), _jsxs("div", { className: 'right-side-footer', children: [_jsx("h3", { children: "Nuestras Redes" }), _jsxs("div", { className: 'social-media', children: [_jsx("img", { src: Github, alt: "github-logo" }), _jsx("a", { href: "http://github.com/JDDev7", target: '_blank', rel: "noreferrer", children: "Mi Github" }), _jsx("p", { children: " / " }), _jsx("a", { href: "https://github.com/JDDev7/yellowjack-react-site", target: '_blank', rel: "noreferrer", children: "Github del proyecto" })] }), _jsxs("div", { className: 'social-media', children: [_jsx("img", { src: LinkedIn, alt: "linkedin-logo" }), _jsx("a", { href: "https://www.linkedin.com/in/jdmorenopulido/", target: '_blank', rel: "noreferrer", children: "LinkedIn" })] }), _jsxs("div", { className: 'social-media', children: [_jsx("img", { src: Twitter, alt: "twitter-logo" }), _jsx("a", { href: "https://www.twitter.com/JDdev_", target: '_blank', rel: "noreferrer", children: "Twitter" })] })] })] }), _jsx("div", { className: 'footer-centered', children: _jsxs("p", { children: ["Copyright \u00A9 JDDev ", new Date().getFullYear(), ". La marca YellowJack pertenece a Rockstar Games. Dise\u00F1o y desarrollo de la web por Jos\u00E9 Diego \"JDDev\" Moreno."] }) })] }) }));
};
export default Footer;
